security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthAuthenticator
            logout:
                path: /api/logout

    access_control:
        - { path: ^/api/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/api/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/, roles: ROLE_USER }
